
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftSOMASUBTRACAOleftMULTIPLICACAODIVISAOrightPOTENCIAABRE_PARENTESES ATRIBUICAO DIVISAO FECHA_PARENTESES FUNCAO ID IGUAL MULTIPLICACAO NUM_FLOAT NUM_INT POTENCIA SOMA SUBTRACAO VIRGULA\nprograma : sentencas\n\nsentencas : sentenca sentencas\n          | sentenca\n\nsentenca : atribuicao\n         | declaracao_funcao\n\natribuicao : ID IGUAL expressao\n\ndeclaracao_funcao : FUNCAO ID ABRE_PARENTESES parametros_formais FECHA_PARENTESES IGUAL expressao\n\nparametros_formais : lista_ids\n                   | empty\n\nlista_ids : ID VIRGULA lista_ids\n          | ID\n\nexpressao : expressao SOMA expressao\n          | expressao SUBTRACAO expressao\n          | expressao MULTIPLICACAO expressao\n          | expressao DIVISAO expressao\n          | expressao POTENCIA expressao\n\nexpressao : SUBTRACAO expressao %prec SOMA\n\nexpressao : ABRE_PARENTESES expressao FECHA_PARENTESES\n\nexpressao : NUM_INT\n          | NUM_FLOAT\n\nexpressao : ID\n\nexpressao : ID ABRE_PARENTESES argumentos FECHA_PARENTESES\n\nargumentos : lista_expressoes\n           | empty\n\nlista_expressoes : expressao VIRGULA lista_expressoes\n                 | expressao\n\nempty :\n'
    
_lr_action_items = {'ID':([0,3,4,5,7,9,11,12,13,14,15,16,17,18,19,20,21,22,23,24,34,35,36,37,38,39,40,42,43,45,47,],[6,6,-4,-5,10,11,-21,-6,11,11,-19,-20,26,11,11,11,11,11,11,-17,-12,-13,-14,-15,-16,-18,26,-22,11,11,-7,]),'FUNCAO':([0,3,4,5,11,12,15,16,24,34,35,36,37,38,39,42,47,],[7,7,-4,-5,-21,-6,-19,-20,-17,-12,-13,-14,-15,-16,-18,-22,-7,]),'$end':([1,2,3,4,5,8,11,12,15,16,24,34,35,36,37,38,39,42,47,],[0,-1,-3,-4,-5,-2,-21,-6,-19,-20,-17,-12,-13,-14,-15,-16,-18,-22,-7,]),'IGUAL':([6,41,],[9,45,]),'SUBTRACAO':([9,11,12,13,14,15,16,18,19,20,21,22,23,24,25,33,34,35,36,37,38,39,42,43,45,47,],[13,-21,20,13,13,-19,-20,13,13,13,13,13,13,-17,20,20,-12,-13,-14,-15,-16,-18,-22,13,13,20,]),'ABRE_PARENTESES':([9,10,11,13,14,18,19,20,21,22,23,43,45,],[14,17,18,14,14,14,14,14,14,14,14,14,14,]),'NUM_INT':([9,13,14,18,19,20,21,22,23,43,45,],[15,15,15,15,15,15,15,15,15,15,15,]),'NUM_FLOAT':([9,13,14,18,19,20,21,22,23,43,45,],[16,16,16,16,16,16,16,16,16,16,16,]),'SOMA':([11,12,15,16,24,25,33,34,35,36,37,38,39,42,47,],[-21,19,-19,-20,-17,19,19,-12,-13,-14,-15,-16,-18,-22,19,]),'MULTIPLICACAO':([11,12,15,16,24,25,33,34,35,36,37,38,39,42,47,],[-21,21,-19,-20,21,21,21,21,21,-14,-15,-16,-18,-22,21,]),'DIVISAO':([11,12,15,16,24,25,33,34,35,36,37,38,39,42,47,],[-21,22,-19,-20,22,22,22,22,22,-14,-15,-16,-18,-22,22,]),'POTENCIA':([11,12,15,16,24,25,33,34,35,36,37,38,39,42,47,],[-21,23,-19,-20,23,23,23,23,23,23,23,23,-18,-22,23,]),'FECHA_PARENTESES':([11,15,16,17,18,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,42,44,46,],[-21,-19,-20,-27,-27,-17,39,-11,41,-8,-9,42,-23,-24,-26,-12,-13,-14,-15,-16,-18,-22,-10,-25,]),'VIRGULA':([11,15,16,24,26,33,34,35,36,37,38,39,42,],[-21,-19,-20,-17,40,43,-12,-13,-14,-15,-16,-18,-22,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'sentencas':([0,3,],[2,8,]),'sentenca':([0,3,],[3,3,]),'atribuicao':([0,3,],[4,4,]),'declaracao_funcao':([0,3,],[5,5,]),'expressao':([9,13,14,18,19,20,21,22,23,43,45,],[12,24,25,33,34,35,36,37,38,33,47,]),'parametros_formais':([17,],[27,]),'lista_ids':([17,40,],[28,44,]),'empty':([17,18,],[29,32,]),'argumentos':([18,],[30,]),'lista_expressoes':([18,43,],[31,46,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> sentencas','programa',1,'p_programa','parser.py',30),
  ('sentencas -> sentenca sentencas','sentencas',2,'p_sentencas','parser.py',36),
  ('sentencas -> sentenca','sentencas',1,'p_sentencas','parser.py',37),
  ('sentenca -> atribuicao','sentenca',1,'p_sentenca','parser.py',46),
  ('sentenca -> declaracao_funcao','sentenca',1,'p_sentenca','parser.py',47),
  ('atribuicao -> ID IGUAL expressao','atribuicao',3,'p_atribuicao','parser.py',53),
  ('declaracao_funcao -> FUNCAO ID ABRE_PARENTESES parametros_formais FECHA_PARENTESES IGUAL expressao','declaracao_funcao',7,'p_declaracao_funcao','parser.py',59),
  ('parametros_formais -> lista_ids','parametros_formais',1,'p_parametros_formais','parser.py',65),
  ('parametros_formais -> empty','parametros_formais',1,'p_parametros_formais','parser.py',66),
  ('lista_ids -> ID VIRGULA lista_ids','lista_ids',3,'p_lista_ids','parser.py',72),
  ('lista_ids -> ID','lista_ids',1,'p_lista_ids','parser.py',73),
  ('expressao -> expressao SOMA expressao','expressao',3,'p_expressao_binaria','parser.py',82),
  ('expressao -> expressao SUBTRACAO expressao','expressao',3,'p_expressao_binaria','parser.py',83),
  ('expressao -> expressao MULTIPLICACAO expressao','expressao',3,'p_expressao_binaria','parser.py',84),
  ('expressao -> expressao DIVISAO expressao','expressao',3,'p_expressao_binaria','parser.py',85),
  ('expressao -> expressao POTENCIA expressao','expressao',3,'p_expressao_binaria','parser.py',86),
  ('expressao -> SUBTRACAO expressao','expressao',2,'p_expressao_unaria','parser.py',92),
  ('expressao -> ABRE_PARENTESES expressao FECHA_PARENTESES','expressao',3,'p_expressao_grupo','parser.py',98),
  ('expressao -> NUM_INT','expressao',1,'p_expressao_numero','parser.py',104),
  ('expressao -> NUM_FLOAT','expressao',1,'p_expressao_numero','parser.py',105),
  ('expressao -> ID','expressao',1,'p_expressao_id','parser.py',111),
  ('expressao -> ID ABRE_PARENTESES argumentos FECHA_PARENTESES','expressao',4,'p_expressao_chamada_funcao','parser.py',117),
  ('argumentos -> lista_expressoes','argumentos',1,'p_argumentos','parser.py',123),
  ('argumentos -> empty','argumentos',1,'p_argumentos','parser.py',124),
  ('lista_expressoes -> expressao VIRGULA lista_expressoes','lista_expressoes',3,'p_lista_expressoes','parser.py',130),
  ('lista_expressoes -> expressao','lista_expressoes',1,'p_lista_expressoes','parser.py',131),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',140),
]
